In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
import warnings
warnings.filterwarnings("ignore")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/CN/cars.csv')
df

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [ ]:
df.isnull().sum()   #null value checking

selling_price    0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 1 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   selling_price  2 non-null      int64
dtypes: int64(1)
memory usage: 144.0 bytes

In [ ]:
df.describe()

       selling_price
count       2.000000
mean   410000.000000
std     56568.542495
min    370000.000000
25%    390000.000000
50%    410000.000000
75%    430000.000000
max    450000.000000